# Generated by Django 4.2.6 on 2023-12-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a genre of movie', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title Movie', max_length=200)),
                ('sologan', models.CharField(default='', help_text='Sologan Movie', max_length=200)),
                ('description', models.TextField(help_text='Enter description of the movie', max_length=2000)),
                ('director', models.CharField(help_text='Director', max_length=100)),
                ('cast', models.CharField(help_text='Cast', max_length=200)),
                ('duration', models.IntegerField(default=0, help_text='Duration of movie')),
                ('poster', models.ImageField(upload_to='poster/')),
                ('trailer_url', models.URLField(help_text='Enter link trailer')),
                ('price', models.IntegerField(default=0, help_text='Price of movie')),
                ('status', models.CharField(choices=[('N', 'Now Showing'), ('C', 'Coming Soon'), ('E', 'End Showing')], default='C', help_text='Movie availability', max_length=1)),
                ('genre', models.ManyToManyField(help_text='Select a genre for this movie', to='App.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ShowingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingdate')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
            ],
        ),
        migrations.CreateModel(
            name='BookingComfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_quantity', models.IntegerField(default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingdate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingtime')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
            ],
        ),
    ]
