# Generated by Django 4.2.6 on 2023-12-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product/')),
                ('status', models.CharField(choices=[('S', 'Soda'), ('P', 'PopCorn'), ('T', 'Tea'), ('C', 'Combo')], default='C', max_length=1)),
            ],
        ),
    ]
