# Generated by Django 4.2.6 on 2023-12-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
            ],
        ),
    ]
