# Generated by Django 4.2.6 on 2023-12-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_productcomfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcomfirm',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcomfirm',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
