# Generated by Django 4.2.6 on 2023-12-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_bookingcomfirm_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomfirm',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
