# Generated by Django 4.2.6 on 2023-12-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_productcomfirm_total_price_completedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedpayment',
            name='user_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.booking'),
        ),
    ]
