# Generated by Django 4.2.6 on 2023-12-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_completedpayment_product_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpayment',
            name='total_price',
        ),
    ]
