# Generated by Django 4.2.6 on 2023-12-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_completedpayment_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpayment',
            name='booking_confirm',
        ),
        migrations.RemoveField(
            model_name='completedpayment',
            name='product_confirm',
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='booking_total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.showingdate'),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.movie'),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.products'),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='product_total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='seats_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.showingtime'),
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='total_complete_payment',
            field=models.IntegerField(null=True),
        ),
    ]
