# Generated by Django 4.2.6 on 2023-12-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_bookingcomfirm_branch_completedpayment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='showingdate',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AddField(
            model_name='showingtime',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
