# Generated by Django 4.2.6 on 2024-01-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_showingdate_branch_showingtime_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteMoviePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], default='F', max_length=1)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingdate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingtime')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
            ],
        ),
    ]
