# Generated by Django 4.2.6 on 2024-01-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_completemoviepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedpayment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='completemoviepayment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
