# Generated by Django 4.2.6 on 2024-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_completedpayment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedpayment',
            name='product',
        ),
        migrations.AddField(
            model_name='completedpayment',
            name='product',
            field=models.ManyToManyField(through='App.ProductOrder', to='App.products'),
        ),
    ]
