# Generated by Django 4.2.6 on 2024-01-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_remove_completedpayment_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], default='F', max_length=1)),
                ('payment_date', models.DateField(null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking')),
            ],
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedPayment',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
