# Generated by Django 4.2.6 on 2024-01-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_completeproductpayment_remove_productorder_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomfirm',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
