# Generated by Django 4.2.6 on 2024-01-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0013_showingdate_branch_showingtime_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seat', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.productsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('staff', models.CharField(max_length=50)),
                ('date_import', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExportDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('staff', models.CharField(max_length=50)),
                ('date_export', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cinemabranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaStatistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie_virual', models.IntegerField()),
                ('product_virual', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('day_of_work', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('M', 'CinemaManager'), ('P', 'ProductManager'), ('S', 'Staff')], default='S', max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('St', 'Standard Seat'), ('Pr', 'Premium Seat'), ('Sw', 'Sweetbox Seat')], default='St', max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemaroom')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phantom', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_seat', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.cinemabranch')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingdate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingtime')),
            ],
        ),
    ]
