# Generated by Django 4.2.6 on 2024-01-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0003_alter_cinemabill_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabill',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
