# Generated by Django 4.2.6 on 2024-01-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_completedpayment_payment_date_and_more'),
        ('AppAdmin', '0005_cinemastatistical_movie_cinemastatistical_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatistical',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
    ]
