# Generated by Django 4.2.6 on 2024-01-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0006_alter_cinemastatistical_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatistical',
            name='movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cinemastatistical',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
