# Generated by Django 4.2.6 on 2024-01-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0007_alter_cinemastatistical_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatistical',
            name='difference',
            field=models.IntegerField(null=True),
        ),
    ]
