# Generated by Django 4.2.6 on 2024-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0008_alter_cinemastatistical_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatistical',
            name='product_virual',
            field=models.IntegerField(null=True),
        ),
    ]
