# Generated by Django 4.2.6 on 2024-01-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0009_alter_cinemastatistical_product_virual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatistical',
            name='movie_virual',
            field=models.IntegerField(null=True),
        ),
    ]
