# Generated by Django 4.2.6 on 2024-01-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_completedpayment_payment_date_and_more'),
        ('AppAdmin', '0010_alter_cinemastatistical_movie_virual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaStatisticalMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movie_virual', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaStatisticalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_virual', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CinemaStatistical',
        ),
    ]
