# Generated by Django 4.2.6 on 2024-01-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_completedpayment_payment_date_and_more'),
        ('AppAdmin', '0011_cinemastatisticalmovie_cinemastatisticalproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatisticalproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products'),
        ),
    ]
