# Generated by Django 4.2.6 on 2024-01-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0012_alter_cinemastatisticalproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemastatisticalproduct',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
