# Generated by Django 4.2.6 on 2024-01-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_productcomfirm_branch'),
        ('AppAdmin', '0013_alter_cinemastatisticalproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaBillMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_seat', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_date', models.DateField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingdate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.showingtime')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaBillProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_date', models.DateField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CinemaBill',
        ),
    ]
