# Generated by Django 4.2.6 on 2024-01-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_productcomfirm_branch'),
        ('AppAdmin', '0014_cinemabillmovie_cinemabillproduct_delete_cinemabill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemabillproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.products'),
        ),
    ]
