# Generated by Django 4.2.6 on 2024-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0015_alter_cinemabillproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemawarehouse',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Stocking'), ('O', 'Out of stock')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='exportdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
